server.host: "0.0.0.0"

# 1. Enable HTTPS for the Kibana Browser UI using the extracted files
server.ssl.enabled: true
server.ssl.certificate: "/etc/kibana/kibana.crt"
server.ssl.key: "/etc/kibana/kibana.key"

# 2. Connect to Elasticsearch over HTTPS
elasticsearch.hosts:
  [
    "https://{{ hostvars[groups['elasticsearch_master'][0]].ansible_host }}:9200",
  ]
elasticsearch.username: "kibana_system"
elasticsearch.password: "Elastic@123"

# 3. Bypass Hostname Verification for dynamic AWS IPs
elasticsearch.ssl.verificationMode: none

# --- 4. Encryption Keys ---
xpack.security.encryptionKey: "{{ kibana_security_encryption_key }}"
xpack.reporting.encryptionKey: "{{ kibana_reporting_encryption_key }}"
xpack.encryptedSavedObjects.encryptionKey: "{{ kibana_saved_objects_encryption_key }}"