---
elastic_cluster_name: "my-elastic-cluster"

elk_version: "7.9.3"

es_seed_hosts:
  - "{{ hostvars['master-node-1'].ansible_host }}"
  - "{{ hostvars['master-eligible-1'].ansible_host }}"

es_master_nodes:
  - "master-node-1"